#FSR Autogenerated Content. DO NOT DELETE
from .debug_remove_session_state import debug_remove_session_state
from .debug_reset_session_state import debug_reset_session_state
from .debug_expire_cookie import debug_expire_cookie
from .get_network_security_policies import get_network_security_policies
from .get_alerts import get_alerts
from .get_workloads import get_workloads
from .get_networks import get_networks
from .get_distributedservicecards import get_distributedservicecards
from .enable_ipfix_export import enable_ipfix_export
from .delete_ipfix_export import delete_ipfix_export
from .enable_mirror_export import enable_mirror_export
from .delete_mirror_export import delete_mirror_export
from .isolate_host import isolate_host
from .unisolate_host import unisolate_host
from .ioc_block_add_ip import ioc_block_add_ip
from .ioc_block_remove_ip import ioc_block_remove_ip
from .ioc_delete_list import ioc_delete_list
 
supported_operations = {'debug_remove_session_state': debug_remove_session_state, 'debug_reset_session_state': debug_reset_session_state, 'debug_expire_cookie': debug_expire_cookie, 'get_network_security_policies': get_network_security_policies, 'get_alerts': get_alerts, 'get_workloads': get_workloads, 'get_networks': get_networks, 'get_distributedservicecards': get_distributedservicecards, 'enable_ipfix_export': enable_ipfix_export, 'delete_ipfix_export': delete_ipfix_export, 'enable_mirror_export': enable_mirror_export, 'delete_mirror_export': delete_mirror_export, 'isolate_host': isolate_host, 'unisolate_host': unisolate_host, 'ioc_block_add_ip': ioc_block_add_ip, 'ioc_block_remove_ip': ioc_block_remove_ip, 'ioc_delete_list': ioc_delete_list, }